export const GET_SURVEYS = 'GET_SURVEYS';
export const GET_SURVEY = 'GET_SURVEY';
export const UPDATE_SURVEYS = 'UPDATE_SURVEYS';
export const ERROR_SURVEYS = 'ERROR_SURVEYS';
export const DELETE_SURVEYS = 'DELETE_SURVEYS';
export const ADD_SURVEYS = 'ADD_SURVEYS';

export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORY = 'GET_CATEGORY';
export const UPDATE_CATEGORIES = 'UPDATE_CATEGORIES';
export const ERROR_CATEGORIES = 'ERROR_CATEGORIES';
export const DELETE_CATEGORIES = 'DELETE_CATEGORIES';
export const ADD_CATEGORIES = 'ADD_CATEGORIES';